### ISSUE TITLE
Solr gets terminated before tests run

### ISSUE THREAD

**Issue by tsujigiri** [collectiveidea/sunspot_test#12]
I'm using sunspot_test with Test::Unit and Shoulda and experience, that Solr gets terminated before the tests run. This does not happen when I comment out the `at_exit` call in `start_sunspot_server`.

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-create it by May 17, 2017. Thanks!
