### ISSUE TITLE
sunspot_test only commits to solr before steps begin

### ISSUE THREAD

**Issue by joelmccracken** [collectiveidea/sunspot_test#13]
Any records created between the running of the Before hooks and the running of the sunspot search will not be added to the Solr index.

I'm not sure what the best way to handle this would be, but it would be nice if the README was clearer about at what stage Sunspot.commit is run, and how that changes the use of the library in testing.

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-create it by May 17, 2017. Thanks!

**Comment by joelmccracken** [comment]
Wow, I don't even remember making this issue!

**Comment by datSunday** [comment]
I'm just facing this issue now... so I guess it's ripe for getting re-created.
