### ISSUE TITLE
 RSolr::Error::Http - 404 Not Found on CircleCI

### ISSUE THREAD

**Issue by anduong** [collectiveidea/sunspot_test#19]
Hi all,
I use cucumber to test solr search by using sunspot_test. I have a problem. 
On local: I passed all the tests.
On CircleCI: I got this error with every feature using ```@search``` tag of sunspot_test

```
@search
Feature: Pagination
  In order to browse books and view searching results with a particular amount
  As a user
  I want to have a feature that I can choose number of books to be displayed

  Scenario: user see pagination feature on browsing books page # features/pagination.feature:7
  RSolr::Error::Http - 404 Not Found
  Error:     Not Found

  Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><delete><query>*:*</query></delete>"
```

How do I fix it? Thanks

**Comment by chrisdolendo** [comment]
Yes, @aponcz was correct. CircleCi generates another sunspot.yml file. I was able to resolve this issue by overriding adding the following to the circleci.yml file:

database:
  override:
    - RAILS_ENV=test bundle exec rake db:create
    - RAILS_ENV=test bundle exec rake db:migrate
    # you'd move your sunspot start command here
    - RAILS_ENV=test bundle exec rake sunspot:solr:start
    - RAILS_ENV=test bundle exec rake db:seed

remove all other redundant  lines involving solr.

All tests passed on my end.

**Comment by anduong** [comment]
Thanks @aponcz  and @chrisdolendo!
