### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by shamus** [collectiveidea/sunspot_test#21]
The v0.4.0 tag predates the change in 89a9ae7167e2c15a22738d77fa6e8812a161e473 that modifies how before blocks are managed for specs tagged `search: true`. 

Can a new version of this gem be published?

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-create it by May 17, 2017. Thanks!
