### ISSUE TITLE
you dont need to call commit after remove_all!

### ISSUE THREAD

**Issue by sevaorlov** [collectiveidea/sunspot_test#22]
Hi, why do you need to invoke `Sunspot.commit` after `Sunspot.remove_all!`?
`remove_all!` will invoke `commit` https://github.com/sunspot/sunspot/blob/ec64df6a526d738f9f77c039679b344f908d3298/sunspot/lib/sunspot/session.rb#L188

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-create it by May 17, 2017. Thanks!
