### ISSUE TITLE
Negative tag syntax  ~@search is not compatible with cucumber 4

### ISSUE THREAD

**Issue by rvalladares77** [collectiveidea/sunspot_test#37]
[sunspot_test/lib/sunspot_test/cucumber.rb](https://github.com/collectiveidea/sunspot_test/blob/master/lib/sunspot_test/cucumber.rb#L7) is using a cucumber old style tag expressions. the `~` for negative tags was removed in the [version 4](https://github.com/cucumber/cucumber-ruby/blob/master/CHANGELOG.md#400rc1-2018-09-29) , so according to cucumber documentation, it should be `not @search` instead of  `~@search`

**Comment by rvalladares77** [comment]
@jonkerz  @manlycode First of all, I want to thank you for your valuable help in creating this PR[#38](https://github.com/collectiveidea/sunspot_test/pull/38)   for this issue. 

I see it was merged, so I tried to upgrade my gem to the newest version 0.4.2 but I am getting this:

`Bundler attempted to update sunspot_test but its version stayed the same `

And also this website https://rubygems.org/gems/sunspot_test shows only the version 0.4.1, Is the version 0.4.2 actually available?

**Comment by manlycode** [comment]
@rvalladares77 Sorry for the delay. I bumped the 0.4.2 version on ruby gems.org.
