### ISSUE TITLE
sunspot_test assumes I'm using Rails

### ISSUE THREAD

**Issue by claco** [collectiveidea/sunspot_test#7]
I'm trying to use sunspot_test in a regular rspec project. Not a Rails project.

The server fails to start because Rails is not loaded:

sunspot_rails-1.2.1/lib/sunspot/rails/configuration.rb:277:in `user_configuration': uninitialized constant Rails (NameError)
    from sunspot_rails-1.2.1/lib/sunspot/rails/configuration.rb:261:in`user_configuration_from_key'
    from sunspot_rails-1.2.1/lib/sunspot/rails/configuration.rb:211:in `solr_home'
    from sunspot_rails-1.2.1/lib/sunspot/rails/server.rb:69:in`solr_home'
    from sunspot_rails-1.2.1/lib/sunspot/rails/server.rb:150:in `install_solr_home'
    from sunspot_rails-1.2.1/lib/sunspot/rails/server.rb:28:in`bootstrap'
    from sunspot_rails-1.2.1/lib/sunspot/rails/server.rb:14:in `run'
    from sunspot_test-0.4.0/lib/sunspot_test.rb:29:in`start_sunspot_server'
    from sunspot_test-0.4.0/lib/sunspot_test.rb:26:in `fork'
    from sunspot_test-0.4.0/lib/sunspot_test.rb:26:in`start_sunspot_server'
    from sunspot_test-0.4.0/lib/sunspot_test.rb:17:in `setup_solr'
    from sunspot_test-0.4.0/lib/sunspot_test/rspec.rb:9
    from rspec-core-2.6.4/lib/rspec/core/hooks.rb:35:in`instance_eval'
    from rspec-core-2.6.4/lib/rspec/core/hooks.rb:35:in `run_in'
    from rspec-core-2.6.4/lib/rspec/core/hooks.rb:70:in`run_all'
    from rspec-core-2.6.4/lib/rspec/core/hooks.rb:70:in `each'
    from rspec-core-2.6.4/lib/rspec/core/hooks.rb:70:in`run_all'
    from rspec-core-2.6.4/lib/rspec/core/hooks.rb:126:in `run_hook_filtered'
    from rspec-core-2.6.4/lib/rspec/core/example_group.rb:206:in`eval_before_alls'
    from rspec-core-2.6.4/lib/rspec/core/example_group.rb:261:in `run'
    from rspec-core-2.6.4/lib/rspec/core/command_line.rb:24:in`run'
    from rspec-core-2.6.4/lib/rspec/core/command_line.rb:24:in `map'
    from rspec-core-2.6.4/lib/rspec/core/command_line.rb:24:in`run'
    from rspec-core-2.6.4/lib/rspec/core/reporter.rb:12:in `report'
    from rspec-core-2.6.4/lib/rspec/core/command_line.rb:21:in`run'
    from rspec-core-2.6.4/lib/rspec/core/runner.rb:80:in `run_in_process'
    from rspec-core-2.6.4/lib/rspec/core/runner.rb:69:in`run'
    from rspec-core-2.6.4/lib/rspec/core/runner.rb:11:in `autorun'
    from rspec:19

**Comment by asheren** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this issue to be addressed, please re-create it by May 17, 2017. Thanks!
